# Generated by Django 3.0.5 on 2020-10-09 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='employee_range',
            new_name='employee_range_id',
        ),
    ]
