# Generated by Django 3.0.5 on 2020-10-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201009_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='coi_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='pan_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
