# Generated by Django 3.0.5 on 2020-10-10 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201009_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ifs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=11)),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Bank')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('pan', models.CharField(blank=True, max_length=10, null=True)),
                ('aadhaar_number', models.CharField(blank=True, max_length=16, null=True)),
                ('permanent_address', models.TextField(blank=True, null=True)),
                ('current_address', models.TextField(blank=True, null=True)),
                ('net_monthly_salary', models.IntegerField()),
                ('service_status', models.IntegerField(blank=True, null=True)),
                ('credit_limit', models.FloatField(blank=True, null=True)),
                ('bank_account_number', models.CharField(max_length=18)),
                ('department_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Department')),
                ('designation_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Designation')),
                ('ifs_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Ifs')),
                ('level_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Level')),
            ],
        ),
    ]
