# Generated by Django 3.0.5 on 2020-10-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_bank_employee_ifs_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='average_monthly_salary_payout',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='monthly_salary_day',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
