# Generated by Django 3.0.5 on 2020-10-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201010_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
