# Generated by Django 3.0.5 on 2020-10-12 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_employee_confirmed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='city_id',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='employee_range_id',
            new_name='employee_range',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='industry_id',
            new_name='industry',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='state_id',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='department_id',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='designation_id',
            new_name='designation',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employee_id',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='ifs_id',
            new_name='ifs',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='level_id',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='ifs',
            old_name='bank_id',
            new_name='bank',
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
