# Generated by Django 3.0.5 on 2020-10-13 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_employee_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee',
            new_name='employee_id',
        ),
    ]
