# Generated by Django 3.0.5 on 2020-10-17 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20201016_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='address_proof',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='id_proof',
        ),
        migrations.DeleteModel(
            name='Kyc',
        ),
    ]
