# Generated by Django 3.0.5 on 2020-10-22 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20201021_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='credited',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='daily_salary',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='debited',
            field=models.FloatField(default=0),
        ),
    ]
