# Generated by Django 3.0.5 on 2020-10-22 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20201022_0430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='weekly_holidays',
        ),
    ]
