# Generated by Django 3.0.5 on 2020-10-22 08:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_employee_weekly_holidays'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='weekly_holidays',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
