# Generated by Django 3.0.5 on 2020-10-22 09:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20201022_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='weekly_holidays',
        ),
        migrations.AddField(
            model_name='employee',
            name='weekly_holidays',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
