# Generated by Django 3.0.5 on 2020-10-23 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20201022_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='weekly_holidays',
        ),
    ]
