# Generated by Django 3.0.5 on 2020-10-23 09:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_employee_weekly_holidays'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='weekly_working_days',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'days': ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']}, null=True),
        ),
    ]
