# Generated by Django 3.0.5 on 2020-10-28 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import dynamic_validator.field_validation.validator


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0028_auto_20201028_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='image/profile/photo/')),
                ('bank_account_number', models.CharField(blank=True, max_length=18, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Company')),
                ('ifs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Ifs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(dynamic_validator.field_validation.validator.ModelFieldRequiredMixin, models.Model),
        ),
    ]
