# Generated by Django 3.0.5 on 2020-10-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='image/profile/photo/'),
        ),
    ]
