# Generated by Django 3.0.5 on 2020-10-29 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20201028_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='ifs',
        ),
        migrations.AddField(
            model_name='employer',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Department'),
        ),
        migrations.AddField(
            model_name='employer',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Designation'),
        ),
    ]
