# Generated by Django 3.0.5 on 2020-10-30 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_employee_last_attendance_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='start_time',
        ),
    ]
