# Generated by Django 3.0.5 on 2020-10-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20201030_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='end_time',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='present',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='start_time',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
