# Generated by Django 3.0.5 on 2020-10-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20201030_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='duration',
            field=models.CharField(blank=True, choices=[('full_day', 'full_day'), ('half_day', 'half_day')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='work_location',
            field=models.CharField(blank=True, choices=[('office', 'office'), ('home', 'home'), ('other', 'other')], max_length=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('date', 'employee', 'company'), name='unique_date_employee_company'),
        ),
    ]
