# Generated by Django 3.0.5 on 2020-10-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20201030_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='last_attendance_on',
        ),
        migrations.AddField(
            model_name='company',
            name='qr_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
