# Generated by Django 3.0.5 on 2020-11-02 04:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
import dynamic_validator.field_validation.validator


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20201030_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_index=True, default=datetime.datetime.now)),
                ('description', models.CharField(max_length=255)),
                ('credit', models.FloatField(null=True)),
                ('debit', models.FloatField(null=True)),
                ('balance', models.FloatField()),
                ('status', models.CharField(choices=[('completed', 'completed'), ('in_progress', 'in_progress'), ('failed', 'failed')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Employee')),
            ],
            bases=(dynamic_validator.field_validation.validator.ModelFieldRequiredMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='statement',
            constraint=models.CheckConstraint(check=models.Q(('debit__isnull', False), ('credit__isnull', False), _connector='OR'), name='not_both_null'),
        ),
    ]
