# Generated by Django 3.0.5 on 2020-11-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20201102_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='date',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
    ]
