# Generated by Django 3.0.5 on 2020-11-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_employee_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='principle_companies',
            field=models.ManyToManyField(blank=True, null=True, related_name='employers', to='core.Company'),
        ),
    ]
