# Generated by Django 3.0.5 on 2020-11-02 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_employer_principle_companies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='principle_companies',
            new_name='principal_companies',
        ),
    ]
