# Generated by Django 3.0.5 on 2020-11-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20201102_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='principal_companies',
            field=models.ManyToManyField(blank=True, related_name='employers', to='core.Company'),
        ),
    ]
