# Generated by Django 3.0.5 on 2020-11-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_auto_20201109_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/attendance/'),
        ),
    ]
