# Generated by Django 3.0.5 on 2020-11-11 10:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_attendance_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_rid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_rid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='employer',
            name='employer_rid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
