# Generated by Django 3.0.5 on 2020-11-11 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20201111_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_rid',
            new_name='rid',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employee_rid',
            new_name='rid',
        ),
        migrations.RenameField(
            model_name='employer',
            old_name='employer_rid',
            new_name='rid',
        ),
    ]
