# Generated by Django 3.0.5 on 2020-11-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20201111_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='category',
            field=models.IntegerField(choices=[(0, 'normal'), (1, 'principal')], default=0),
        ),
    ]
