# Generated by Django 3.0.5 on 2020-11-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_company_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='work_timings',
            field=models.CharField(default='9AM-6PM', max_length=18, null=True),
        ),
    ]
