# Generated by Django 3.0.5 on 2020-11-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_auto_20201117_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_beneficiary',
            field=models.BooleanField(default=False),
        ),
    ]
