# Generated by Django 3.0.5 on 2020-11-20 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_employee_is_beneficiary'),
        ('core', '0058_auto_20201118_1613'),
    ]

    operations = [
    ]
