# Generated by Django 3.0.5 on 2020-11-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_merge_20201120_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='service_status',
            field=models.IntegerField(default=0),
        ),
    ]
