# Generated by Django 3.0.5 on 2020-11-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_auto_20201120_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary_type',
            field=models.CharField(default='net', max_length=50),
        ),
    ]
