# Generated by Django 3.0.5 on 2020-11-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_auto_20201120_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='credited',
            field=models.FloatField(default=0),
        ),
    ]
