# Generated by Django 3.0.5 on 2020-11-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_auto_20201120_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='statement',
            name='otp_valid_till',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
