# Generated by Django 3.0.5 on 2020-12-01 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_qrcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='company',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='company',
            name='qr_id',
        ),
    ]
