# Generated by Django 3.0.5 on 2020-12-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_auto_20201201_0656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='designation',
        ),
        migrations.AddField(
            model_name='booking',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'employee'), (2, 'employer')], null=True),
        ),
    ]
