# Generated by Django 3.0.5 on 2020-12-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_auto_20201218_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='category',
            field=models.CharField(blank=True, choices=[('employee', 'employee'), ('employer', 'employer')], max_length=8, null=True),
        ),
    ]
