# Generated by Django 3.0.5 on 2020-12-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_auto_20201218_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'employee'), (2, 'employer')], null=True),
        ),
    ]
