# Generated by Django 3.0.5 on 2020-12-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_auto_20201218_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
