# Generated by Django 3.0.5 on 2020-12-23 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_company_code'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendance',
            name='unique_date_employee_company',
        ),
    ]
