# Generated by Django 3.0.5 on 2020-12-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_auto_20201226_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='category',
            field=models.IntegerField(choices=[(0, 'contractor'), (1, 'principal_employer')], default=0),
        ),
    ]
