# Generated by Django 3.0.5 on 2020-12-26 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_auto_20201226_0909'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='qrcode',
            name='unique_qr_id_longitude_latitude',
        ),
    ]
