# Generated by Django 3.0.5 on 2020-12-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_auto_20201226_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='qr_id',
            field=models.CharField(max_length=23, unique=True),
        ),
    ]
