# Generated by Django 3.0.5 on 2020-12-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_auto_20201226_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='check_location',
            field=models.BooleanField(default=True),
        ),
    ]
