# Generated by Django 3.0.5 on 2020-12-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
