# Generated by Django 3.0.5 on 2021-01-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_statement_rid'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='fcm_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
