# Generated by Django 3.0.5 on 2021-01-07 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_employee_fcm_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='fcm_id',
            new_name='fcm_registration_token',
        ),
    ]
