# Generated by Django 3.0.5 on 2021-01-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_auto_20210107_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='domain',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
