# Generated by Django 3.0.5 on 2021-01-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_auto_20210113_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='domain',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
