# Generated by Django 3.0.5 on 2021-01-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_auto_20210113_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='mail_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='mail_token',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='unsubscribe_token',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
