# Generated by Django 3.0.5 on 2021-01-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_auto_20210114_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mail_token',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='unsubscribe_token',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
