# Generated by Django 3.0.5 on 2021-01-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_auto_20210114_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mail_token',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='unsubscribe_token',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
