# Generated by Django 3.0.5 on 2021-01-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_auto_20210115_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
