# Generated by Django 3.0.5 on 2021-01-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='min_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
