# Generated by Django 3.0.5 on 2021-01-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_auto_20210121_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='closing_balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statement',
            name='opening_balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
