# Generated by Django 3.0.5 on 2021-01-21 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_auto_20210121_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statement',
            name='balance',
        ),
    ]
