# Generated by Django 3.0.5 on 2021-01-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_remove_statement_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
