# Generated by Django 3.0.5 on 2021-01-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_auto_20210125_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
