# Generated by Django 3.0.5 on 2021-01-25 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_employee_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statement',
            name='status',
        ),
    ]
