# Generated by Django 3.0.5 on 2021-01-25 08:43

import core.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_auto_20210125_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='work_days',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=core.models.get_default_work_days),
        ),
    ]
