# Generated by Django 3.0.5 on 2021-01-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_auto_20210125_0843'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('date', 'employee', 'company'), name='make_unique_date_employee_company'),
        ),
    ]
