# Generated by Django 3.0.5 on 2021-01-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_remove_employee_fcm_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='mail_bounced',
            field=models.IntegerField(default=0),
        ),
    ]
