# Generated by Django 3.0.5 on 2021-01-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_employee_mail_bounced'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='company_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='mail_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='verified_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
