# Generated by Django 3.0.5 on 2021-02-01 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0115_auto_20210130_0752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Employee')),
            ],
        ),
    ]
