# Generated by Django 3.0.5 on 2021-02-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_verifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='wish_listing',
            field=models.BooleanField(default=False),
        ),
    ]
