# Generated by Django 3.0.5 on 2021-02-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_employee_wish_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='salary',
            field=models.FloatField(default=0),
        ),
    ]
