# Generated by Django 3.0.5 on 2021-02-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_auto_20210208_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifier',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
