# Generated by Django 3.0.5 on 2021-02-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0123_auto_20210210_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='credit_limit',
            field=models.FloatField(blank=True, default=50, null=True),
        ),
    ]
