# Generated by Django 3.0.5 on 2021-02-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0124_auto_20210211_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='credit_limit',
            field=models.FloatField(default=50),
        ),
    ]
