# Generated by Django 3.0.5 on 2021-02-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0125_auto_20210211_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='subscription_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
