# Generated by Django 3.0.5 on 2021-02-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0126_company_subscription_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='e_nach',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='kyc',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
