# Generated by Django 3.0.5 on 2021-02-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0127_auto_20210212_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='verified_salary',
            field=models.FloatField(default=0),
        ),
    ]
