# Generated by Django 3.0.5 on 2021-02-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0128_attendance_verified_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='subscription_amount',
            field=models.FloatField(default=0),
        ),
    ]
