# Generated by Django 3.0.5 on 2021-02-16 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0130_domain_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='domain',
            new_name='domain_name',
        ),
    ]
