# Generated by Django 3.0.5 on 2021-02-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0132_domain_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
    ]
