# Generated by Django 3.0.5 on 2021-02-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0136_auto_20210218_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='fees',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='gst',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='withdraw',
            field=models.FloatField(default=0),
        ),
    ]
