# Generated by Django 3.0.5 on 2021-02-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0137_auto_20210219_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
