# Generated by Django 3.0.5 on 2021-03-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0138_employee_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='digital_time_stamp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statement',
            name='digital_time_stamp',
            field=models.TextField(blank=True, null=True),
        ),
    ]
