# Generated by Django 3.0.5 on 2021-03-26 12:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0142_employee_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='extra_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
