# Generated by Django 3.0.5 on 2021-03-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0143_employee_extra_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(db_index=True, max_length=30, null=True),
        ),
    ]
