# Generated by Django 3.0.5 on 2021-03-26 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0145_auto_20210326_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(db_index=True, default=datetime.datetime.now),
        ),
    ]
