# Generated by Django 3.0.5 on 2021-03-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0146_auto_20210326_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
