# Generated by Django 3.0.5 on 2020-05-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_valid_till',
            field=models.DateTimeField(null=True),
        ),
    ]
