# Generated by Django 3.0.5 on 2020-10-12 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_company_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='department_id',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='designation_id',
            new_name='designation',
        ),
    ]
