# Generated by Django 3.0.5 on 2020-05-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_account_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
