# Generated by Django 3.0.5 on 2020-05-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_worker_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_beneficiary',
            field=models.BooleanField(default=False),
        ),
    ]
