# Generated by Django 3.0.5 on 2020-05-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_account_is_beneficiary'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='beneficiary_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
