# Generated by Django 3.0.5 on 2020-05-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0006_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='transfer_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
