# Generated by Django 3.0.5 on 2020-05-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0008_auto_20200510_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
