# Generated by Django 3.0.5 on 2020-05-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0009_worker_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='fcm_registration_token',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
