# Generated by Django 3.0.5 on 2020-05-25 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0010_worker_fcm_registration_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('transfer_id', models.CharField(max_length=20, null=True)),
                ('utr', models.CharField(max_length=30, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('detail', models.CharField(max_length=150, null=True)),
                ('processed_on', models.DateTimeField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workers.Account')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workers.Worker')),
            ],
        ),
    ]
