# Generated by Django 3.0.5 on 2020-06-08 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0011_advance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punch_in', models.DateTimeField()),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workers.Worker')),
            ],
        ),
    ]
