# Generated by Django 3.0.5 on 2020-06-11 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0012_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='punch_in',
            new_name='punch_at',
        ),
    ]
